kind: Service
apiVersion: v1
metadata:
   name: my-service
spec:
   selector:
      app: gcr
   ports:
           - protocol: TCP
             port: 80
             targetPort: 8080
   type: LoadBalancer
